### ISSUE TITLE
Fix Task output and error handling for docker resources

### ISSUE THREAD

**Issue by agrare** [ManageIQ/floe#111]
When a docker resource is completed we use the container logs to feed the output / error handling of the Task state.

Currently the entirety of stdout+stderr is considered but this breaks down quickly when you consider that other libraries might be logging to stdout/stderr and also that you want to log progress during a long running container and only print output at the end.

We are suggesting that a delimiter be printed once a container has completed and is printing output for task output consideration and everything after that point will be considered for task output.

**Comment by agrare** [comment]
cc @kbrock

**Comment by kbrock** [comment]
We also have the need for the docker container to log output.

As mentioned elsewhere, a typical lambda process has 3 output channels: `stdout`, `stderr`, and `data` (via `return`).

We have condensed down to a single channel. While `stderr` and `stdout` can be consolidated to a `logging` channel, we still need to separate out the `data`.

We also need to know if there was a success of a failure.
If the process is connecting to an http endpoint, printing out the stack trace 

```
connecting to provider
fetching values
retrieved values
__FLOE__OUTPUT__
{"value": "Yay"}
```

Not sure the best way to include an error and a cause, but we can possibly choose a delimiter, or use the same delimiter and use a common format.

```
error on line 18
called from 15
called from 12
__FLOE__OUTPUT__
{"Error": "Timeout", "Cause": "Could not connect to api within 1 minute"}
```

or

```
...
__FLOE__ERROR__OUTPUT__
{"Error": "Timeout", "Cause": "Could not connect to api within 1 minute"}
```

**Comment by Fryguy** [comment]
> We have condensed down to a single channel.

Not sure I understand this - docker supports stderr and stdout in the logging. Does `docker logs` not support that split?  Or is this a podman or kubernetes thing?  Just want to make sure I understand this comment correctly before moving on.

**Comment by agrare** [comment]
docker and podman have stdout/stderr split up, kubernetes doesn't
