### ISSUE TITLE
Do not allow --net host

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/floe#77]
Extracted from the discussion in https://github.com/ManageIQ/floe/pull/52#discussion_r1278113931

---

> @Fryguy
> As discussed, we should avoid --net host
> 
> it will definitely require rewriting some of the examples, so I'm ok to merge for now, but then we need a followup issue to remove it.
> 
> @agrare
> Yeah we should probably discuss this separately since this isn't new code.
> 
> Docker isn't used for production only development and localhost:3000 is 99% of the development use cases so we can remove this if we want but it will require significant changes for developers' workflows
> 
> I get not everyone would use docker only for development so we could add a runner option set by the caller.

**Comment by Fryguy** [comment]
Yes, for development this gets a lot more complicated if the author can't do `--net host`.

What I'm thinking, for now, would be a Floe-class-level boolean option where we can enable or disable `--net host` with the default disabled.  Then, on the Rails side when we set up Floe, we can do something roughly like:

```ruby
Floe.allow_net_host = Rails.env.development? || Rails.env.test?
```

Alternatively, we could allow it per-workflow and extend that option to the workflow itself, but that feels like pushing down too much about the runtime environment into the workflow, which is not where it really belongs, IMO.

**Comment by agrare** [comment]
:+1: I think runner-level makes sense since this option would apply to docker and podman but not kubernetes.
